sudo: required
language: ruby
cache: bundler
script: scripts/travis.sh
services:
  - docker
jobs:
  include:
  - rvm: 2.5
    env: STAGE=test
  - rvm: 2.6
    env: STAGE=test
  - rvm: 2.7
    env: STAGE=test

  - rvm: 2.5
    env: STAGE=typecheck
  - rvm: 2.6
    env: STAGE=typecheck
  - rvm: 2.7
    env: STAGE=typecheck

  - rvm: 2.7
    env: STAGE=integration
