sudo: required
language: ruby
script: scripts/travis.sh
before_install:
  - source ~/.nvm/nvm.sh && nvm install 15.0.1
services:
  - docker
rvm:
  - 2.5.8
  # - 2.6.6
  # - 2.7.2
env:
  # - STAGE=test
  # - STAGE=typecheck
  - STAGE=integration
