name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Bundler and Prebundler
        run: gem install bundler prebundler
      - name: Lock Dependencies
        run: bundle lock
      - name: Install Dependencies
        run: prebundle install --jobs 2 --retry 3
        env:
          PREBUNDLER_ACCESS_KEY_ID: "${{ secrets.PREBUNDLER_ACCESS_KEY_ID }}"
          PREBUNDLER_SECRET_ACCESS_KEY: "${{ secrets.PREBUNDLER_SECRET_ACCESS_KEY }}"
      - name: Run Tests
        run: bundle exec rspec
