name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: install bundler
        run: gem install bundler
      - name: bundle
        run: bundle install --jobs 2 --retry 3
      - name: rspec
        run: bundle exec rspec
